"""Regenerate the machine-derived docs:  python -m scripts.export_docs

Writes docs/openapi.json, docs/api-endpoints.md and docs/workflow-graph.md from the real application objects,
so they cannot drift from the code.
"""

from __future__ import annotations

import json
import tempfile
from pathlib import Path

from langgraph.checkpoint.memory import MemorySaver

from app.config import Settings
from app.database import Base, make_engine
from app.graph.builder import NODE_LABELS, build_graph
from app.main import create_app
from app.services.container import build_container

DOCS = Path(__file__).resolve().parents[2] / "docs"


def main() -> None:
    tmp = Path(tempfile.mkdtemp())
    settings = Settings(_env_file=None, app_env="test", database_url=f"sqlite:///{tmp}/d.db", llm_provider="mock", upload_dir=str(tmp / "u"),
                        secret_key="docs-docs-docs-docs-docs-docs-docs-docs")  # noqa: S106
    engine = make_engine(settings.database_url)
    Base.metadata.create_all(engine)
    container = build_container(settings, engine=engine, qdrant_in_memory=True)
    app = create_app(settings, container)
    spec = app.openapi()
    DOCS.mkdir(exist_ok=True)
    (DOCS / "openapi.json").write_text(json.dumps(spec, indent=1))

    rows = []
    for path, ops in sorted(spec["paths"].items()):
        for method, op in ops.items():
            secured = "public" if path in ("/health", "/ready") or path.endswith("/auth/login") or path.endswith("/auth/register") else "bearer token"
            rows.append((op.get("tags", [""])[0], method.upper(), path, op.get("summary", "").replace("|", "/"), secured))
    rows.sort(key=lambda r: (r[0], r[2], r[1]))
    lines = ["# API endpoint reference", "", "_Generated by `python -m scripts.export_docs` from the live OpenAPI schema. "
             "Interactive docs are served at `/docs` outside production._", "", "| Area | Method | Path | Summary | Auth |", "|---|---|---|---|---|"]
    lines += [f"| {t} | {m} | `{p}` | {s} | {a} |" for t, m, p, s, a in rows]
    (DOCS / "api-endpoints.md").write_text("\n".join(lines) + "\n")

    graph = build_graph(container, MemorySaver()).get_graph()
    mermaid = graph.draw_mermaid()
    names = sorted(n for n in graph.nodes if not n.startswith("__"))
    body = ["# Workflow graph", "", "_Generated by `python -m scripts.export_docs` from the compiled LangGraph._", "",
            f"{len(names)} nodes. One `plan_<category>` node exists per registered project category.", "", "```mermaid", mermaid.strip(), "```", "",
            "## Nodes", "", "| Node | Label shown in the UI |", "|---|---|"]
    body += [f"| `{n}` | {NODE_LABELS.get(n, n)} |" for n in names]
    (DOCS / "workflow-graph.md").write_text("\n".join(body) + "\n")
    print(f"wrote {len(rows)} endpoints and {len(names)} graph nodes to {DOCS}")


if __name__ == "__main__":
    main()
